add components section
tscircuit/circuit-json-to-readable-netlist pull request #3
Opened 2024-12-29 10:36 UTC by Anshgrover23

/claim #2 
Fixes #2

2024-12-29 14:39 UTC, Abse2001 commented
@Anshgrover23 and use `bun run format` before pushing.

2024-12-29 15:06 UTC, Anshgrover23 commented
@Abse2001 `bun run format` is not setup in this repository.

2024-12-29 18:28 UTC, seveibar requested changes

2024-12-29 18:28 UTC, seveibar commented on lib/convertCircuitJsonToReadableNetlist.ts
> +      ` - ${component.name}: ${component.manufacturer_part_number || "N/A"}, ${supplierNumbers}`,
i wouldn't add N/A here- it's confusing because there's no indication of what's supposed to be there. Also a part number being not-applicable is not a concept i'm familiar with

For resistors, you need to add the resistor `display_resistance` and for capacitors you need to add the `display_capactance`, also the footprinter string if it is available (the issue showed an example of this)

2024-12-29 18:28 UTC, seveibar commented on tests/test1-basic-circuit.test.tsx
> + - C1: N/A, N/A
not good... don't put N/A anywhere

2024-12-29 18:28 UTC, seveibar commented on tests/test2-chip.test.tsx
> + - U1: CL05B102KB5NNNC, digikey: 1276-1018-1-ND; mouser: 187-CL05B102KB5NNNC; lcsc: C89040
remove supplier part numbers from the implementation, i don't think it's helpful in the context of a netlist. We probably need something like a part description here, but we don't have that inside circuit-json yet

2024-12-30 15:48 UTC, ShiboSoftwareDev commented on lib/convertCircuitJsonToReadableNetlist.ts
> +      footprint = cadComponent.footprinter_string || "unknown footprint"
or statement is not needed

2024-12-30 17:52 UTC, seveibar requested changes

2024-12-30 17:52 UTC, seveibar commented on tests/test2-chip.test.tsx
> + - U1: U1 soic8 simple_chip
This should have manufacturer part number instead of “simple_chip”

2024-12-30 18:28 UTC, hunnywar commented on tests/test2-chip.test.tsx
> + - U1: U1 soic8 simple_chip
done.

2024-12-30 18:30 UTC, seveibar approved these changes

2024-12-30 18:30 UTC, merged